export type IndonesiaProvince = {
  region_id: string;
  name: string;
};

export const INDONESIA_PROVINCES: IndonesiaProvince[] = [
  { region_id: "11", name: "Aceh" },
  { region_id: "12", name: "Sumatera Utara" },
  { region_id: "13", name: "Sumatera Barat" },
  { region_id: "14", name: "Riau" },
  { region_id: "15", name: "Jambi" },
  { region_id: "16", name: "Sumatera Selatan" },
  { region_id: "17", name: "Bengkulu" },
  { region_id: "18", name: "Lampung" },
  { region_id: "19", name: "Kepulauan Bangka Belitung" },
  { region_id: "21", name: "Kepulauan Riau" },
  { region_id: "31", name: "DKI Jakarta" },
  { region_id: "32", name: "Jawa Barat" },
  { region_id: "33", name: "Jawa Tengah" },
  { region_id: "34", name: "DI Yogyakarta" },
  { region_id: "35", name: "Jawa Timur" },
  { region_id: "36", name: "Banten" },
  { region_id: "51", name: "Bali" },
  { region_id: "52", name: "Nusa Tenggara Barat" },
  { region_id: "53", name: "Nusa Tenggara Timur" },
  { region_id: "61", name: "Kalimantan Barat" },
  { region_id: "62", name: "Kalimantan Tengah" },
  { region_id: "63", name: "Kalimantan Selatan" },
  { region_id: "64", name: "Kalimantan Timur" },
  { region_id: "65", name: "Kalimantan Utara" },
  { region_id: "71", name: "Sulawesi Utara" },
  { region_id: "72", name: "Sulawesi Tengah" },
  { region_id: "73", name: "Sulawesi Selatan" },
  { region_id: "74", name: "Sulawesi Tenggara" },
  { region_id: "75", name: "Gorontalo" },
  { region_id: "76", name: "Sulawesi Barat" },
  { region_id: "81", name: "Maluku" },
  { region_id: "82", name: "Maluku Utara" },
  { region_id: "91", name: "Papua" },
  { region_id: "92", name: "Papua Barat" },
  { region_id: "93", name: "Papua Selatan" },
  { region_id: "94", name: "Papua Tengah" },
  { region_id: "95", name: "Papua Pegunungan" },
  { region_id: "96", name: "Papua Barat Daya" },
];
