export const TABLES = {
  USERS: "users",
  USER_ASSIGNMENTS: "user_assignments",
  AVAILABLE_LOCATIONS: "available_locations",
  BIOFLOC_THEMATIC_PROGRAMS: "biofloc_thematic_programs",
  PROPOSAL_BIOFLOC_THEMATIC_PROGRAMS: "proposal_biofloc_thematic_programs",
  PROGRAM_QUOTAS: "program_quotas",
  LOGS: "monitoring_logs",
  UPT: "technical_units",
  KDMP_ENTITIES: "kdmp_entities",
  REF_PROVINCES: "ref_provinces",
  REF_REGENCIES: "ref_regencies",
  REF_DISTRICTS: "ref_districts",
  REF_VILLAGES: "ref_villages",
} as const;
