CREATE TABLE IF NOT EXISTS kdmp_entities (
  -- biarkan id auto increment agar join tetap efisien (BIGSERIAL)
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 

  -- Identitas Kelompok
  name TEXT NOT NULL,
  name_search TEXT GENERATED ALWAYS AS (lower(name)) STORED,

  -- Legalitas (diverifikasi via API external)
  kusuka_number TEXT,
  kusuka_verified BOOLEAN DEFAULT FALSE,
  nib TEXT,
  legal_entity_number TEXT,

  -- Pengurus
  chairman_name TEXT,
  chairman_phone TEXT,
  companion_name TEXT,
  companion_phone TEXT,
  board_member_count INTEGER DEFAULT 0,
  member_count INTEGER DEFAULT 0,

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_kdmp_name_search ON kdmp_entities (name_search);
CREATE INDEX idx_kdmp_kusuka ON kdmp_entities (kusuka_number);
GRANT ALL ON TABLE kdmp_entities TO anon, authenticated, service_role;
