CREATE TABLE thematic_programs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_id BIGINT REFERENCES available_locations(id),

  type VARCHAR(20) NOT NULL CHECK (type IN ('biofloc', 'minapadi')),

  name TEXT NOT NULL,
  percentage_of_work INTEGER CHECK (percentage_of_work BETWEEN 0 AND 100),
  commodity TEXT NOT NULL,
  land_area TEXT NOT NULL,
  production TEXT NOT NULL,
  total_admin INTEGER NOT NULL,
  distribution_amount INTEGER NOT NULL,
  sppg_partner TEXT NOT NULL,

  s_curve_path TEXT,
  documentations TEXT DEFAULT '[]',
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

GRANT ALL ON TABLE thematic_programs TO anon, authenticated, service_role;
