CREATE TABLE proposal_biofloc_thematic_programs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_id BIGINT REFERENCES available_locations(id),
  province_id TEXT NOT NULL, -- id provinsi
  regency_id TEXT NOT NULL, -- id kabupaten

  -- status 
  status VARCHAR(20) NOT NULL,

  name TEXT NOT NULL, -- nama kdmp
  name_search TEXT GENERATED ALWAYS AS (lower(name)) STORED, -- nama kdmp untuk search (lowercase)

  district TEXT NOT NULL, -- nama kelurahan
  village TEXT NOT NULL, -- nama desa
  
  proposal_path TEXT NOT NULL,

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- INDEXING: Agar pencarian nama kelompok (KDMP) secepat kilat
CREATE INDEX idx_proposals_name_search ON proposal_biofloc_thematic_programs (name_search);

-- INDEXING TAMBAHAN: Untuk mempermudah filtering provinsi (karena ada 34-38 data)
CREATE INDEX idx_proposals_province ON proposal_biofloc_thematic_programs (province_id);

GRANT ALL ON TABLE proposal_biofloc_thematic_programs TO anon, authenticated, service_role;
