CREATE TABLE documentations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_type VARCHAR(50) NOT NULL, -- biofloc_thematic, minapadi_thematic, isf
  program_id BIGINT NOT NULL, -- id of the program
  type VARCHAR(25) CHECK (type IN ('before', 'after')) NOT NULL, -- before or after
  path TEXT NOT NULL, -- path to the file
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_documentations_program_type_program_id ON documentations(program_type, program_id);

-- Create trigger to update updated_at
CREATE OR REPLACE FUNCTION handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  return NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to update updated_at for documentations table
CREATE TRIGGER set_updated_at
BEFORE UPDATE ON documentations
FOR EACH ROW
EXECUTE PROCEDURE handle_updated_at();