CREATE TABLE program_quotas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  region_id TEXT NOT NULL,

  program_type TEXT NOT NULL,
  year INTEGER NOT NULL,
  quota INTEGER NOT NULL DEFAULT 0,

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE(region_id, program_type, year)
);

GRANT ALL ON TABLE program_quotas TO anon, authenticated, service_role;
