CREATE TABLE IF NOT EXISTS program_quotas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  province_id TEXT NOT NULL, -- code from Kemendagri

  program_type TEXT NOT NULL,
  year INTEGER NOT NULL,
  quota_limit INTEGER NOT NULL DEFAULT 0,

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE(province_id, program_type, year)
);

-- Index for searching and filtering
CREATE INDEX idx_quotas_province ON program_quotas (province_id);
CREATE INDEX idx_quotas_program_type ON program_quotas (program_type);

GRANT ALL ON TABLE program_quotas TO anon, authenticated, service_role;
