CREATE TABLE proposal_biofloc_thematic_programs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- status 
  status VARCHAR(20) NOT NULL,

  name TEXT NOT NULL, -- nama kdmp

  province TEXT NOT NULL, -- nama pronvisi
  regency TEXT NOT NULL, -- nama kabupaten
  district TEXT NOT NULL, -- nama kelurahan
  village TEXT NOT NULL, -- nama desa

  proposal_path TEXT NOT NULL,

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

GRANT ALL ON TABLE proposal_biofloc_thematic_programs TO anon, authenticated, service_role;
