CREATE TABLE isf_program_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  step_id INTEGER NOT NULL CHECK (step_id BETWEEN 1 AND 7),

  progress_percent INTEGER CHECK (progress_percent BETWEEN 0 AND 100),
  progress_date DATE NOT NULL,
  reporting_week DATE NOT NULL,

  name TEXT NOT NULL,
  status TEXT NOT NULL,
  provider_name TEXT NOT NULL,
  production TEXT NOT NULL,
  intervention TEXT NOT NULL,
  total_worker INTEGER NOT NULL,

  outcome TEXT NOT NULL,
  constraints TEXT NOT NULL,
  follow_up TEXT NOT NULL,

  s_curve_path TEXT,

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE(step_id, reporting_week)
);

CREATE INDEX idx_logs_step_date 
ON isf_program_logs (step_id, progress_date DESC);

CREATE INDEX idx_logs_date 
ON isf_program_logs (progress_date);