CREATE TABLE isf_programs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_id BIGINT REFERENCES available_locations(id),
  name TEXT NOT NULL,
  percentage_of_work INTEGER CHECK (percentage_of_work BETWEEN 0 AND 100),
  documentations JSONB NOT NULL DEFAULT '[]',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
