CREATE TABLE thematic_programs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_id BIGINT REFERENCES available_locations(id),
  name TEXT NOT NULL,
  percentage_of_work INTEGER CHECK (percentage_of_work BETWEEN 0 AND 100),
  commodity TEXT NOT NULL,
  land_area TEXT NOT NULL,
  production TEXT NOT NULL,
  total_admin INTEGER NOT NULL,
  distribution_amount INTEGER NOT NULL,
  sppg_partner TEXT NOT NULL,
  s_curve_path VARCHAR(255) NOT NULL,
  documentations JSONB NOT NULL DEFAULT '[]',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
