CREATE TABLE IF NOT EXISTS program_quotas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  province_code TEXT NOT NULL REFERENCES ref_provinces(code),
  province_name TEXT NOT NULL,

  program_type TEXT NOT NULL, -- biofloc_thematic, isf, etc
  year INTEGER NOT NULL,
  quota_limit INTEGER NOT NULL DEFAULT 0,

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE(province_code, program_type, year)
);

-- Index for searching and filtering
CREATE INDEX idx_quotas_province_code ON program_quotas (province_code);
CREATE INDEX idx_quotas_program_type ON program_quotas (program_type);

GRANT ALL ON TABLE program_quotas TO anon, authenticated, service_role;
