-- Create User Assignments table for granular role and scope management
CREATE TABLE IF NOT EXISTS public.user_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    role TEXT NOT NULL,
    program_scope TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    -- Ensure unique combinations for each assignment
    UNIQUE(user_id, role, program_scope),

    -- Integrity constraints
    CONSTRAINT check_role CHECK (role IN ('admin', 'officer', 'leader', 'viewer', 'pmo')),
    CONSTRAINT check_program_scope CHECK (program_scope IN ('biofloc', 'minapadi', 'isf', 'revitalisasi', 'all', 'none'))
);

-- Disable RLS
ALTER TABLE public.user_assignments DISABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE user_assignments TO anon, authenticated, service_role;
