CREATE TABLE IF NOT EXISTS available_locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- standardrize kemendagri code
  province_id TEXT NOT NULL, -- 31 for jakarta (2 digit)
  regency_id TEXT NOT NULL, -- 3171 for jakarta pusat (4 digit)

  type VARCHAR(50) NOT NULL, -- biofloc_thematic, isf
  name TEXT NOT NULL, -- name of the location

  -- location
  latitude DECIMAL(10, 8) NOT NULL,
  longitude DECIMAL(11, 8) NOT NULL,

  -- timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for regional filtering
CREATE INDEX idx_locations_province ON available_locations (province_id);
CREATE INDEX idx_locations_regency ON available_locations (regency_id);

GRANT ALL ON TABLE available_locations TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;