CREATE TABLE biofloc_thematic_programs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_id BIGINT REFERENCES available_locations(id),

  -- status of program
  status VARCHAR(20) NOT NULL CHECK (status IN ('potential', 'active', 'inactive')),

  -- fetch on outside API
  kusuka_number TEXT NOT NULL,

  name TEXT NOT NULL,
  percentage_of_work INTEGER CHECK (percentage_of_work BETWEEN 0 AND 100),
  commodity TEXT NOT NULL,
  land_area TEXT NOT NULL,
  production TEXT NOT NULL,
  total_admin INTEGER NOT NULL,
  distribution_amount INTEGER NOT NULL,
  sppg_partner TEXT NOT NULL,

  s_curve_path TEXT,
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

GRANT ALL ON TABLE biofloc_thematic_programs TO anon, authenticated, service_role;
