CREATE TABLE IF NOT EXISTS minapadi_thematic_programs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_id BIGINT REFERENCES available_locations(id),
  
  -- status of program
  status VARCHAR(20) NOT NULL CHECK (status IN ('potential', 'active', 'inactive')),
  name TEXT NOT NULL,

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

GRANT ALL ON TABLE minapadi_thematic_programs TO anon, authenticated, service_role;
