CREATE TABLE IF NOT EXISTS available_locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Wilayah FK ke reference tables (kode Kemendagri, dot-separated)
  province_code TEXT NOT NULL REFERENCES ref_provinces(code),   -- '32'
  province_name TEXT NOT NULL, -- denormalization for easy access to fetch data for map

  regency_code TEXT NOT NULL REFERENCES ref_regencies(code),    -- '32.01'
  district_code TEXT REFERENCES ref_districts(code),            -- '32.01.01'
  village_code TEXT REFERENCES ref_villages(code),              -- '32.01.01.2001'

  type VARCHAR(50) NOT NULL,  -- biofloc_thematic, minapadi_thematic
  name TEXT NOT NULL,         -- cached display name

  latitude DECIMAL(10, 8) NOT NULL,
  longitude DECIMAL(11, 8) NOT NULL,

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for regional filtering
CREATE INDEX idx_locations_province_code ON available_locations (province_code);
CREATE INDEX idx_locations_regency_code ON available_locations (regency_code);
CREATE INDEX idx_locations_district_code ON available_locations (district_code);
CREATE INDEX idx_locations_village_code ON available_locations (village_code);

GRANT ALL ON TABLE available_locations TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;