CREATE TABLE program_priority_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  available_location_id BIGINT REFERENCES available_locations(id),
  name TEXT NOT NULL,
  provider_type TEXT CHECK(provider_type IN('private', 'institution')),
  percentage_of_work INTEGER CHECK (percentage_of_work BETWEEN 0 AND 100),
  status TEXT CHECK (status IN ('HUB', 'NON-HUB')),
  constraints TEXT,
  follow_up TEXT,
  documentations JSONB DEFAULT '[]',
  created_at TIMESTAMPTZ DEFAULT NOW()
);
