CREATE TABLE program_priority_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  available_location_id BIGINT REFERENCES available_locations(id),
  name TEXT NOT NULL,
  provider_type TEXT NOT NULL,
  percentage_of_work INTEGER CHECK (percentage_of_work BETWEEN 0 AND 100),
  status TEXT NOT NULL,
  constraints TEXT NOT NULL,
  follow_up TEXT NOT NULL,
  documentations JSONB DEFAULT '[]',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
